services:
  web:
    image: ghcr.io/airlangga07/mikaelairlangga-site:${WEB_TAG:-latest}
    restart: unless-stopped
    ports:
      - "3001:3000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - web
